about:blank:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing. firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/cde-c6c444a2addfba5c71ccad8d5d94a7a2e5126a66/static/node_modules/vsda/rust/web/vsda_bg.wasm:1
           Failed to load resource: the server responded with a status of 404 ()
firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/cde-c6c444a2addfba5c71ccad8d5d94a7a2e5126a66/static/node_modules/vsda/rust/web/vsda.js:1

           Failed to load resource: the server responded with a status of 404 ()
firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/cde-c6c444a2addfba5c71ccad8d5d94a7a2e5126a66/static/node_modules/vsda/rust/web/vsda_bg.wasm:1

           Failed to load resource: the server responded with a status of 404 ()
firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/cde-c6c444a2addfba5c71ccad8d5d94a7a2e5126a66/static/node_modules/vsda/rust/web/vsda.js:1

           Failed to load resource: the server responded with a status of 404 ()
VM43 node_modules_next_dist_client_43e3ffb8._.js:1194 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        lang="en"
-                       pwa-launched="true"
-                       pwa-extension-id="npnbdojkgkbcdfdjlfdmplppdphlhhcf"
-                       pwa-extension-url-root="chrome-extension://npnbdojkgkbcdfdjlfdmplppdphlhhcf/"
-                       className="pwa-dark-mode"
                      >
                    ...
        ...

error @ VM43 node_modules_next_dist_client_43e3ffb8._.js:1194
VM43 node_modules_next_dist_client_43e3ffb8._.js:1194 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        lang="en"
-                       pwa-launched="true"
-                       pwa-extension-id="npnbdojkgkbcdfdjlfdmplppdphlhhcf"
-                       pwa-extension-url-root="chrome-extension://npnbdojkgkbcdfdjlfdmplppdphlhhcf/"
-                       className="pwa-dark-mode"
                      >
                    ...
        ...

error @ VM43 node_modules_next_dist_client_43e3ffb8._.js:1194
VM43 node_modules_next_dist_client_43e3ffb8._.js:14247 WebSocket connection to 'wss://6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ VM43 node_modules_next_dist_client_43e3ffb8._.js:14247
VM43 node_modules_next_dist_client_43e3ffb8._.js:14247 WebSocket connection to 'wss://6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ VM43 node_modules_next_dist_client_43e3ffb8._.js:14247
VM43 node_modules_next_dist_client_43e3ffb8._.js:1194 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

%s%s https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        lang="en"
-                       pwa-launched="true"
-                       pwa-extension-id="npnbdojkgkbcdfdjlfdmplppdphlhhcf"
-                       pwa-extension-url-root="chrome-extension://npnbdojkgkbcdfdjlfdmplppdphlhhcf/"
                      >
                    ...
        ...

error @ VM43 node_modules_next_dist_client_43e3ffb8._.js:1194
VM38 node_modules_next_dist_3bfaed20._.js:804 Image with src "https://placehold.co/300x200.png?text=B0f2hklknb" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.
warnOnce @ VM38 node_modules_next_dist_3bfaed20._.js:804
6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/image?url=https%3A%2F%2Fplacehold.co%2F300x200.png%3Ftext%3DB0f2hklknb&w=256&q=75:1

           Failed to load resource: the server responded with a status of 403 ()
6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/image?url=https%3A%2F%2Fplacehold.co%2F300x200.png%3Ftext%3DB0f2hklknb&w=256&q=75:1

           Failed to load resource: the server responded with a status of 403 ()
VM43 node_modules_next_dist_client_43e3ffb8._.js:14247 WebSocket connection to 'wss://6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ VM43 node_modules_next_dist_client_43e3ffb8._.js:14247
VM43 node_modules_next_dist_client_43e3ffb8._.js:1194 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        lang="en"
-                       pwa-launched="true"
-                       pwa-extension-id="npnbdojkgkbcdfdjlfdmplppdphlhhcf"
-                       pwa-extension-url-root="chrome-extension://npnbdojkgkbcdfdjlfdmplppdphlhhcf/"
-                       className="pwa-dark-mode"
                      >
                    ...
        ...

error @ VM43 node_modules_next_dist_client_43e3ffb8._.js:1194
VM43 node_modules_next_dist_client_43e3ffb8._.js:14247 WebSocket connection to 'wss://6000-firebase-studio-1748821311895.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ VM43 node_modules_next_dist_client_43e3ffb8._.js:14247
VM43 node_modules_next_dist_client_43e3ffb8._.js:1194 Error composing review: TypeError: Failed to fetch
    at fetchServerAction (VM43 node_modules_next_dist_client_43e3ffb8._.js:17651:23)
error @ VM43 node_modules_next_dist_client_43e3ffb8._.js:1194
onSubmit @ VM229 src_c383ef2a._.js:663
layout.tsx:16 A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
                      <html
                        lang="en"
-                       pwa-launched="true"
-                       pwa-extension-id="npnbdojkgkbcdfdjlfdmplppdphlhhcf"
-                       pwa-extension-url-root="chrome-extension://npnbdojkgkbcdfdjlfdmplppdphlhhcf/"
-                       className="pwa-dark-mode"
                      >
                    ...
        ...

error @ intercept-console-error.ts:41
(anonymous) @ react-dom-client.development.js:13501
runWithFiberInDEV @ react-dom-client.development.js:1510
emitPendingHydrationWarnings @ react-dom-client.development.js:13500
completeWork @ react-dom-client.development.js:13661
runWithFiberInDEV @ react-dom-client.development.js:1513
completeUnitOfWork @ react-dom-client.development.js:15255
performUnitOfWork @ react-dom-client.development.js:15136
workLoopConcurrentByScheduler @ react-dom-client.development.js:15113
renderRootConcurrent @ react-dom-client.development.js:15088
performWorkOnRoot @ react-dom-client.development.js:14409
performWorkOnRootViaSchedulerTask @ react-dom-client.development.js:16274
performWorkUntilDeadline @ scheduler.development.js:45
<html>
RootLayout @ layout.tsx:16
(anonymous) @ react-server-dom-turbopack-client.browser.development.js:2328
initializeModelChunk @ react-server-dom-turbopack-client.browser.development.js:1027
getOutlinedModel @ react-server-dom-turbopack-client.browser.development.js:1300
parseModelString @ react-server-dom-turbopack-client.browser.development.js:1513
(anonymous) @ react-server-dom-turbopack-client.browser.development.js:2267
initializeModelChunk @ react-server-dom-turbopack-client.browser.development.js:1027
resolveModelChunk @ react-server-dom-turbopack-client.browser.development.js:1004
resolveModel @ react-server-dom-turbopack-client.browser.development.js:1572
processFullStringRow @ react-server-dom-turbopack-client.browser.development.js:2261
processFullBinaryRow @ react-server-dom-turbopack-client.browser.development.js:2206
progress @ react-server-dom-turbopack-client.browser.development.js:2452
<RootLayout>
buildFakeTask @ react-server-dom-turbopack-client.browser.development.js:2013
initializeFakeTask @ react-server-dom-turbopack-client.browser.development.js:2000
resolveDebugInfo @ react-server-dom-turbopack-client.browser.development.js:2036
processFullStringRow @ react-server-dom-turbopack-client.browser.development.js:2234
processFullBinaryRow @ react-server-dom-turbopack-client.browser.development.js:2206
progress @ react-server-dom-turbopack-client.browser.development.js:2452
"use server"
ResponseInstance @ react-server-dom-turbopack-client.browser.development.js:1560
createResponseFromOptions @ react-server-dom-turbopack-client.browser.development.js:2369
exports.createFromReadableStream @ react-server-dom-turbopack-client.browser.development.js:2681
[project]/node_modules/next/dist/client/app-index.js [app-client] (ecmascript) @ app-index.tsx:158
(anonymous) @ dev-base.ts:205
runModuleExecutionHooks @ dev-base.ts:265
instantiateModule @ dev-base.ts:203
getOrInstantiateModuleFromParent @ dev-base.ts:132
commonJsRequire @ runtime-utils.ts:241
(anonymous) @ app-next-turbopack.ts:9
(anonymous) @ app-bootstrap.ts:78
loadScriptsInSequence @ app-bootstrap.ts:20
appBootstrap @ app-bootstrap.ts:60
[project]/node_modules/next/dist/client/app-next-turbopack.js [app-client] (ecmascript) @ app-next-turbopack.ts:8
(anonymous) @ dev-base.ts:205
runModuleExecutionHooks @ dev-base.ts:265
instantiateModule @ dev-base.ts:203
getOrInstantiateRuntimeModule @ dev-base.ts:101
registerChunk @ runtime-backend-dom.ts:85
await in registerChunk
registerChunk @ runtime-base.ts:329
(anonymous) @ dev-backend-dom.ts:127
(anonymous) @ dev-backend-dom.ts:127